---
# tasks file for sa-pm2
  - include_tasks: tasks_nodejs.yml
    when: option_install_nodejs and option_nodejs_install_with_apt

  - include_tasks: tasks_nvm.yml
    when: option_install_nodejs and option_nodejs_install_with_nvm

  - include_tasks: tasks_pm2.yml
